-- Generated from the canonical 125-word curriculum.
-- Run after supabase/schema.sql. Safe to re-run.

insert into public.lessons (id, number, title, subtitle) values
  ('foundations-01', 1, 'Foundations 1', 'Day 1-5'),
  ('foundations-02', 2, 'Foundations 2', 'Day 6-10'),
  ('foundations-03', 3, 'Connectors 3', 'Day 11-15'),
  ('foundations-04', 4, 'Connectors 4', 'Day 16-20'),
  ('foundations-05', 5, 'Places & Time 5', 'Day 21-25'),
  ('foundations-06', 6, 'Places & Time 6', 'Day 26-30'),
  ('foundations-07', 7, 'Belief 7', 'Day 31-35'),
  ('foundations-08', 8, 'Belief 8', 'Day 36-40'),
  ('foundations-09', 9, 'People & Creation 9', 'Day 41-45'),
  ('foundations-10', 10, 'People & Creation 10', 'Day 46-50'),
  ('foundations-11', 11, 'Questions 11', 'Day 51-55'),
  ('foundations-12', 12, 'Questions 12', 'Day 56-60'),
  ('foundations-13', 13, 'Negation 13', 'Day 61-65'),
  ('foundations-14', 14, 'Negation 14', 'Day 66-70'),
  ('foundations-15', 15, 'Guidance 15', 'Day 71-75'),
  ('foundations-16', 16, 'Guidance 16', 'Day 76-80'),
  ('foundations-17', 17, 'Actions 17', 'Day 81-85'),
  ('foundations-18', 18, 'Actions 18', 'Day 86-90'),
  ('foundations-19', 19, 'Pronouns 19', 'Day 91-95'),
  ('foundations-20', 20, 'Pronouns 20', 'Day 96-100'),
  ('foundations-21', 21, 'Quranic Essentials 21', 'Day 101-105'),
  ('foundations-22', 22, 'Quranic Essentials 22', 'Day 106-110'),
  ('foundations-23', 23, 'Review & Recall 23', 'Day 111-115'),
  ('foundations-24', 24, 'Review & Recall 24', 'Day 116-120'),
  ('foundations-25', 25, 'Building Fluency 25', 'Day 121-125')
on conflict (id) do update set number = excluded.number, title = excluded.title, subtitle = excluded.subtitle;

insert into public.words (id, arabic, transliteration, meaning, bengali_meaning, options, gender, source) values
  ('word-1', 'هَذَا', 'Hādhā', 'This', 'এটা', '{''That (ওটা)'',''These (এইসকল)'',''Who (কে)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-2', 'هَـذِهِ', 'Hādhihi', 'This', 'এটা', '{''That (ওটা)'',''Those (সেগুলো)'',''Where (কোথায়)''}'::text[], 'Female, Singular', 'curated-100'),
  ('word-3', 'هَـؤُلآءِ', 'Hā''ulā''i', 'These', 'এইসকল', '{''That (ওটা)'',''This (এটা)'',''You (তুমি)''}'::text[], 'Plural', 'curated-100'),
  ('word-4', 'ذَلِكَ', 'Dhālika', 'That', 'যাহা, যে', '{''This (এটা)'',''These (এইসকল)'',''How (কেমন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-5', 'تِلْكَ', 'Tilka', 'That', 'যাহা, যে', '{''This (এটা)'',''These (এইসকল)'',''What (কী)''}'::text[], 'Female, Singular', 'curated-100'),
  ('word-6', 'أُولَئِكَ', 'Ulā''ika', 'Those', 'যাহারা, সেগুলো', '{''This (এটা)'',''Who (যে)'',''Which (যেটি)''}'::text[], 'Plural', 'curated-100'),
  ('word-7', 'اَلَّذِىْ', 'Alladhī', 'Who/That', 'যে', '{''Which (যেটি)'',''What (কী)'',''When (কখন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-8', 'اَلَّتِىْ', 'Allatī', 'Who/That', 'যে', '{''Why (কেন)'',''How (কেমন)'',''That (ওটা)''}'::text[], 'Female, Singular', 'curated-100'),
  ('word-9', 'اَلَّذِيْنَ', 'Alladhīna', 'Those who', 'তোমরা যারা', '{''These (এইসকল)'',''We (আমরা)'',''All (সব)''}'::text[], 'Plural', 'curated-100'),
  ('word-10', 'تَحْتَ', 'Taḥta', 'Under', 'তলদেশে, নিচে', '{''Above (উপর)'',''Right (ডান)'',''Between (মধ্যে)''}'::text[], 'None', 'curated-100'),
  ('word-11', 'فَوْقَ', 'Fawqa', 'Above', 'উপর', '{''Below (নিচে)'',''Beside (পাশে)'',''With (সাথে)''}'::text[], 'None', 'curated-100'),
  ('word-12', 'قَبْلَ', 'Qabla', 'Before', 'সামনে, আগে', '{''After (পরে)'',''In (মধ্যে)'',''From (থেকে)''}'::text[], 'None', 'curated-100'),
  ('word-13', 'بَﻌْﺪَ', 'Baʿda', 'After', 'পরে, পরবর্তী কালে', '{''Before (আগে)'',''Above (উপরে)'',''Near (কাছে)''}'::text[], 'None', 'curated-100'),
  ('word-14', 'بَيْنَ', 'Bayna', 'Between', 'মধ্যবর্তী স্থানে', '{''Under (নিচে)'',''With (সাথে)'',''Against (বিরুদ্ধে)''}'::text[], 'None', 'curated-100'),
  ('word-15', 'دُونَ', 'Dūna', 'Besides', 'তুলনায়, পার্শ্বে', '{''Before (আগে)'',''On (উপরে)'',''Within (ভিতরে)''}'::text[], 'None', 'curated-100'),
  ('word-16', 'عِنْدَ', 'ʿInda', 'Near', 'নিকটবর্তী, প্রায়', '{''Far (দূরে)'',''On (উপরে)'',''Over (উপরে)''}'::text[], 'None', 'curated-100'),
  ('word-17', 'يَمِيْنْ', 'Yamīn', 'Right', 'ন্যায়, ঠিক, সত্য', '{''Left (বাম)'',''Up (উপরে)'',''Down (নিচে)''}'::text[], 'None', 'curated-100'),
  ('word-18', 'شِمَالْ', 'Shimāl', 'Left', 'বাদিক', '{''Right (ডান)'',''In (মধ্যে)'',''Outside (বাহিরে)''}'::text[], 'None', 'curated-100'),
  ('word-19', 'ٱللَّه', 'Allah', 'Allah', 'আল্লাহ', '{''God (ঈশ্বর)'',''Messenger (দূত)'',''Believer (বিশ্বাসী)''}'::text[], 'None', 'curated-100'),
  ('word-20', 'رَب', 'Rabb', 'Lord', 'রব', '{''King (বাদশাহ)'',''Prophet (নবী)'',''Angel (ফেরেশতা)''}'::text[], 'None', 'curated-100'),
  ('word-21', 'أَرْض', 'Arḍ', 'World/Earth', 'পৃথিবী', '{''Sky (আকাশ)'',''Fire (আগুন)'',''Water (পানি)''}'::text[], 'None', 'curated-100'),
  ('word-22', 'قَوْم', 'Qawm', 'Nation', 'জাতি', '{''Family (পরিবার)'',''People (মানুষ)'',''City (শহর)''}'::text[], 'None', 'curated-100'),
  ('word-23', 'آيَة', 'Āyah', 'Sign/Verse', 'চিহ্ন/আয়াত', '{''Book (কিতাব)'',''Command (নির্দেশ)'',''Truth (সত্য)''}'::text[], 'None', 'curated-100'),
  ('word-24', 'كُل', 'Kullu', 'Every/All', 'প্রত্যেক, সব', '{''Some (কিছু)'',''One (এক)'',''None (কিছু না)''}'::text[], 'None', 'curated-100'),
  ('word-25', 'رَسُول', 'Rasūl', 'Messenger', 'দূত', '{''King (রাজা)'',''Prophet (নবী)'',''Servant (গোলাম)''}'::text[], 'None', 'curated-100'),
  ('word-26', 'يَوْم', 'Yawm', 'Day', 'দিন', '{''Night (রাত)'',''Week (সপ্তাহ)'',''Month (মাস)''}'::text[], 'None', 'curated-100'),
  ('word-27', 'عَذَاب', 'ʿAdhāb', 'Punishment', 'আজাব', '{''Mercy (দয়া)'',''Forgiveness (ক্ষমা)'',''Blessing (আশীর্বাদ)''}'::text[], 'None', 'curated-100'),
  ('word-28', 'سَمَآء', 'Samā''', 'Sky', 'আকাশ', '{''Earth (পৃথিবী)'',''Fire (আগুন)'',''Water (পানি)''}'::text[], 'None', 'curated-100'),
  ('word-29', 'شَىْء', 'Shay''', 'Thing', 'জিনিস, ঘটনা', '{''Person (ব্যক্তি)'',''Place (স্থান)'',''Time (সময়)''}'::text[], 'None', 'curated-100'),
  ('word-30', 'كِتَاب', 'Kitāb', 'Book', 'কিতাব', '{''Pen (কলম)'',''Letter (চিঠি)'',''Word (শব্দ)''}'::text[], 'None', 'curated-100'),
  ('word-31', 'حَق', 'Ḥaqq', 'Truth', 'সত্য', '{''Falsehood (মিথ্যা)'',''Justice (ন্যায়)'',''Mercy (দয়া)''}'::text[], 'None', 'curated-100'),
  ('word-32', 'نَاس', 'Nās', 'People', 'সম্প্রদায়', '{''Believer (বিশ্বাসী)'',''Prophet (নবী)'',''Nation (জাতি)''}'::text[], 'None', 'curated-100'),
  ('word-33', 'مِن', 'Min', 'From', 'হতে, থেকে', '{''To (প্রতি)'',''On (উপরে)'',''In (মধ্যে)''}'::text[], 'None', 'curated-100'),
  ('word-34', 'فِى', 'Fī', 'In', 'অভ্যন্তরে, মধ্যে', '{''On (উপরে)'',''To (প্রতি)'',''From (থেকে)''}'::text[], 'None', 'curated-100'),
  ('word-35', 'عَلَى', 'ʿAlā', 'Upon', 'সন্নিকটে', '{''Under (নিচে)'',''In (মধ্যে)'',''Near (কাছে)''}'::text[], 'None', 'curated-100'),
  ('word-36', 'إِلَى', 'Ilā', 'To', 'কাছে, প্রতি', '{''From (থেকে)'',''With (সাথে)'',''About (সম্পর্কে)''}'::text[], 'None', 'curated-100'),
  ('word-37', 'عَن', 'ʿAn', 'About', 'সম্পর্কিত', '{''To (প্রতি)'',''From (থেকে)'',''In (মধ্যে)''}'::text[], 'None', 'curated-100'),
  ('word-38', 'حَتَّی', 'Ḥattā', 'Until', 'যতক্ষণ না', '{''After (পরে)'',''Before (আগে)'',''When (কখন)''}'::text[], 'None', 'curated-100'),
  ('word-39', 'مَعَ', 'Maʿa', 'With', 'একত্রে, সঙ্গে', '{''Without (ছাড়া)'',''On (উপরে)'',''Under (নিচে)''}'::text[], 'None', 'curated-100'),
  ('word-40', 'بِ', 'Bi', 'With', 'সাথে', '{''For (জন্য)'',''From (থেকে)'',''To (প্রতি)''}'::text[], 'None', 'curated-100'),
  ('word-41', 'كَ', 'Ka', 'Like', 'মত, প্রায়', '{''As (যেমন)'',''For (জন্য)'',''By (দ্বারা)''}'::text[], 'None', 'curated-100'),
  ('word-42', 'لِ', 'Li', 'For', 'জন্য', '{''To (প্রতি)'',''From (থেকে)'',''In (মধ্যে)''}'::text[], 'None', 'curated-100'),
  ('word-43', 'مَن', 'Man', 'Who', 'যে', '{''What (কী)'',''When (কখন)'',''How (কেমন)''}'::text[], 'None', 'curated-100'),
  ('word-44', 'مَا / مَاذَا', 'Mā / Mādhā', 'What', 'কী, যাহা', '{''Who (যে)'',''Where (কোথায়)'',''Why (কেন)''}'::text[], 'None', 'curated-100'),
  ('word-45', 'أَيْنَ', 'Ayna', 'Where', 'যেথায়, কোথায়', '{''When (কখন)'',''Why (কেন)'',''How (কেমন)''}'::text[], 'None', 'curated-100'),
  ('word-46', 'مَتَى', 'Matā', 'When', 'কখন, তখন', '{''What (কী)'',''Where (কোথায়)'',''Who (কে)''}'::text[], 'None', 'curated-100'),
  ('word-47', 'لِمَ / لِمَاذَا', 'Lima / Limādhā', 'Why', 'কেন, কী জন্য', '{''How (কেমন)'',''When (কখন)'',''What (কী)''}'::text[], 'None', 'curated-100'),
  ('word-48', 'كَيْفَ', 'Kayfa', 'How', 'কেমন, কিভাবে', '{''Why (কেন)'',''What (কী)'',''Where (কোথায়)''}'::text[], 'None', 'curated-100'),
  ('word-49', 'هَلْ', 'Hal', 'Are', 'হয় - a question particle', '{''Is not (নয়)'',''Never (কখনও না)'',''Yes (হ্যাঁ)''}'::text[], 'None', 'curated-100'),
  ('word-50', 'أَيُّ', 'Ayyu', 'Which', 'যেটি, যেগুলো', '{''Who (যে)'',''What (কী)'',''Where (কোথায়)''}'::text[], 'None', 'curated-100'),
  ('word-51', 'كَمْ', 'Kam', 'How much', 'কতোটুকু', '{''How many (কত)'',''How long (কতক্ষণ)'',''How far (কতদূর)''}'::text[], 'None', 'curated-100'),
  ('word-52', 'لَا', 'Lā', 'No', 'না', '{''Yes (হ্যাঁ)'',''Maybe (হয়তো)'',''Not (নয়)''}'::text[], 'None', 'curated-100'),
  ('word-53', 'مَا', 'Mā', 'Not', 'মোটেই নয়', '{''Never (কখনও না)'',''No (না)'',''Yes (হ্যাঁ)''}'::text[], 'None', 'curated-100'),
  ('word-54', 'لَمْ', 'Lam', 'Not', 'নয়', '{''Never (কখনও না)'',''No (না)'',''Yes (হ্যাঁ)''}'::text[], 'None', 'curated-100'),
  ('word-55', 'لَنْ', 'Lan', 'Never', 'কখনও না', '{''Not (নয়)'',''No (না)'',''Yes (হ্যাঁ)''}'::text[], 'None', 'curated-100'),
  ('word-56', 'كَلَّا', 'Kallā', 'Nay', 'বস্তুত', '{''Yes (হ্যাঁ)'',''Maybe (হয়তো)'',''Never (কখনও না)''}'::text[], 'None', 'curated-100'),
  ('word-57', 'لَيْسَ', 'Laysa', 'It is not', 'মতো নয়', '{''It is (হয়)'',''There is (আছে)'',''There is not (নেই)''}'::text[], 'None', 'curated-100'),
  ('word-58', 'بَلَى', 'Balā', 'Of course', 'নিশ্চয়ই', '{''Never (কখনও না)'',''No (না)'',''Perhaps (সম্ভবত)''}'::text[], 'None', 'curated-100'),
  ('word-59', 'نَعَمْ', 'Naʿam', 'Yes', 'হ্যাঁ', '{''No (না)'',''Never (কখনও না)'',''Perhaps (সম্ভবত)''}'::text[], 'None', 'curated-100'),
  ('word-60', 'مُؤْمِن', 'Mu''min', 'Believer', 'বিশ্বাসী', '{''Disbeliever (অবিশ্বাসী)'',''Prophet (নবী)'',''Sinner (পাপী)''}'::text[], 'None', 'curated-100'),
  ('word-61', 'سَبِيل', 'Sabīl', 'Way', 'পথ, উপায়', '{''End (শেষ)'',''Beginning (শুরু)'',''Stop (থামা)''}'::text[], 'None', 'curated-100'),
  ('word-62', 'أَمْر', 'Amr', 'Command', 'আজ্ঞা, নির্দেশ', '{''Question (প্রশ্ন)'',''Request (অনুরোধ)'',''Wish (ইচ্ছা)''}'::text[], 'None', 'curated-100'),
  ('word-63', 'بَعْض', 'Baʿḍ', 'Some', 'কেহ, কিছু', '{''All (সব)'',''None (কিছু না)'',''Every (প্রত্যেক)''}'::text[], 'None', 'curated-100'),
  ('word-64', 'خَيْر', 'Khayr', 'Better', 'উত্তম, শ্রেষ্ঠ', '{''Worse (খারাপ)'',''Good (ভাল)'',''Bad (খারাপ)''}'::text[], 'None', 'curated-100'),
  ('word-65', 'إِلَٰه', 'Ilāh', 'Deity', 'ইলাহ', '{''Human (মানুষ)'',''Angel (ফেরেশতা)'',''King (রাজা)''}'::text[], 'None', 'curated-100'),
  ('word-66', 'آخِر', 'Ākhir', 'Last', 'শেষ', '{''First (প্রথম)'',''Middle (মধ্য)'',''Next (পরবর্তী)''}'::text[], 'None', 'curated-100'),
  ('word-67', 'جَنَّة', 'Jannah', 'Garden', 'বাগান', '{''Hell (জাহান্নাম)'',''Sky (আকাশ)'',''Earth (পৃথিবী)''}'::text[], 'None', 'curated-100'),
  ('word-68', 'نَار', 'Nār', 'Fire', 'আগুন', '{''Water (পানি)'',''Air (বাতাস)'',''Earth (পৃথিবী)''}'::text[], 'None', 'curated-100'),
  ('word-69', 'غَيْر', 'Ghayr', 'Without', 'ব্যতিরেকে, ব্যতীত', '{''With (সাথে)'',''Before (আগে)'',''After (পরে)''}'::text[], 'None', 'curated-100'),
  ('word-70', 'قَلْب', 'Qalb', 'Heart', 'অন্তর', '{''Head (মাথা)'',''Hand (হাত)'',''Body (শরীর)''}'::text[], 'None', 'curated-100'),
  ('word-71', 'عَبْد', 'ʿAbd', 'Slave', 'গোলাম', '{''Master (প্রভু)'',''Friend (বন্ধু)'',''Son (পুত্র)''}'::text[], 'None', 'curated-100'),
  ('word-72', 'أَهْل', 'Ahl', 'Family', 'দল, পরিবার', '{''Enemy (শত্রু)'',''Friend (বন্ধু)'',''Guest (অতিথি)''}'::text[], 'None', 'curated-100'),
  ('word-73', 'يَد', 'Yad', 'Hand', 'আয়ত্তে, হাত', '{''Foot (পা)'',''Head (মাথা)'',''Eye (চোখ)''}'::text[], 'None', 'curated-100'),
  ('word-74', 'قَالَ', 'Qāla', 'He said', 'বলেছেন', '{''He did (করেছেন)'',''He knew (জানতেন)'',''He came (এসেছিলেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-75', 'كَانَ', 'Kāna', 'He was', 'He was', '{''He will be'',''He is not'',''He was not''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-76', 'ءَامَنَ', 'Āmana', 'He believed', 'তিনি বিশ্বাস করেছিলেন', '{''He denied (অস্বীকার)'',''He doubted (সন্দেহ)'',''He disbelieved (অবিশ্বাস)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-77', 'عَلِمَ', 'ʿAlima', 'He knew', 'তিনি জানতেন', '{''He saw (দেখেছিলেন)'',''He said (বলেছিলেন)'',''He did (করেছিলেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-78', 'جَعَلَ', 'Jaʿala', 'He made', 'তৈরী করেছেন', '{''He created (সৃষ্টি)'',''He destroyed (ধ্বংস)'',''He gave (দিয়েছেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-79', 'كَفَرَ', 'Kafara', 'He disbelieved', 'অবিশ্বাস করেছিলো', '{''He believed (বিশ্বাস)'',''He knew (জানতেন)'',''He feared (ভয়)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-80', 'جَآءَ', 'Jā''a', 'He came', 'He came', '{''He went'',''He said'',''He saw''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-81', 'عَمِلَ', 'ʿAmila', 'He did', 'করেছিলেন', '{''He said (বলেছিলেন)'',''He believed (বিশ্বাস)'',''He knew (জানতেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-82', 'آتَى', 'Ātā', 'He gave', 'তিনি দিয়েছেন/লেন', '{''He took (নিয়েছেন)'',''He saw (দেখেছেন)'',''He came (এসেছেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-83', 'رَأَى', 'Ra''ā', 'He saw', 'তিনি দেখেছিলেন', '{''He heard (শুনেছিলেন)'',''He knew (জানতেন)'',''He found (পেয়েছিলেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-84', 'أَتَى', 'Atā', 'He came', 'তিনি এসেছিলেন', '{''He went (গিয়েছিলেন)'',''He stayed (থেকেছিলেন)'',''He left (ত্যাগ করেছিলেন)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-85', 'شَآءَ', 'Shā''a', 'He wished', 'ইচ্ছে পোষণ করেছিলেন', '{''He commanded (নির্দেশ)'',''He created (সৃষ্টি)'',''He loved (ভালবাসা)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-86', 'خَلَقَ', 'Khalaqa', 'He created', 'তিনি তৈরী করেছেন', '{''He destroyed (ধ্বংস)'',''He made (তৈরী)'',''He built (নির্মাণ)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-87', 'أَنزَلَ', 'Anzala', 'He sent down', 'তিনি প্রেরণ করলেন', '{''He sent up (উপরে পাঠানো)'',''He made (তৈরী)'',''He created (সৃষ্টি)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-88', 'كَذَّبَ', 'Kadhdhaba', 'He denied', 'মিথ্যে বলা, অস্বীকার করা', '{''He told the truth (সত্য)'',''He confirmed (নিশ্চিত)'',''He believed (বিশ্বাস)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-89', 'دَعَا', 'Daʿā', 'He invoked', 'প্রার্থনা করা অর্থে', '{''He commanded (নির্দেশ)'',''He forbade (নিষেধ)'',''He answered (উত্তর)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-90', 'ٱتَّقَى', 'Attaqā', 'He feared', 'ভয়', '{''He loved (ভালবাসা)'',''He believed (বিশ্বাস)'',''He disobeyed (অবাধ্য)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-91', 'هَدَى', 'Hadā', 'He guided', 'পরিচালিত করলেন', '{''He misled (বিপথে চালিত)'',''He punished (শাস্তি)'',''He helped (সাহায্য)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-92', 'هُوَ', 'Huwa', 'He', 'তিনি, সে', '{''I (আমি)'',''You (তুমি)'',''They (তারা)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-93', 'هُمَا', 'Humā', 'They both', 'উভয়েই', '{''We (আমরা)'',''You both (তোমরা উভয়েই)'',''They (তারা)''}'::text[], 'Male/Female, Dual', 'curated-100'),
  ('word-94', 'هُمْ', 'Hum', 'They', 'তারা', '{''We (আমরা)'',''You (তোমরা)'',''He (তিনি)''}'::text[], 'Male, Plural', 'curated-100'),
  ('word-95', 'هِيَ', 'Hiya', 'She', 'সে', '{''He (তিনি)'',''You (তুমি)'',''I (আমি)''}'::text[], 'Female, Singular', 'curated-100'),
  ('word-96', 'هُنَّ', 'Hunna', 'They', 'তারা', '{''We (আমরা)'',''You (তোমরা)'',''He (তিনি)''}'::text[], 'Female, Plural', 'curated-100'),
  ('word-97', 'أَنْتَ', 'Anta', 'You', 'তুমি', '{''He (সে)'',''I (আমি)'',''We (আমরা)''}'::text[], 'Male, Singular', 'curated-100'),
  ('word-98', 'أَنْتُمَا', 'Antumā', 'You both', 'তোমরা উভয়েই', '{''I (আমি)'',''They both (তারা উভয়)'',''We (আমরা)''}'::text[], 'Male/Female, Dual', 'curated-100'),
  ('word-99', 'أَنَا', 'Anā', 'I', 'আমি', '{''We (আমরা)'',''You (তুমি)'',''He (সে)''}'::text[], 'Male/Female, Singular', 'curated-100'),
  ('word-100', 'نَحْنُ', 'Naḥnu', 'We', 'আমরা', '{''I (আমি)'',''They (তারা)'',''You (তোমরা)''}'::text[], 'Male/Female, Plural', 'curated-100'),
  ('word-101', 'السلام عليكم', 'As-salamu alaykum', 'Peace be upon you', 'আপনার উপর শান্তি বর্ষিত হোক', '{''He knew (তিনি জানতেন)'',''Not (মোটেই নয়)'',''Sky (আকাশ)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-102', 'وعليكم السلام', 'Wa alaykum as-salam', 'And peace be upon you', 'এবং আপনার উপরও শান্তি বর্ষিত হোক', '{''Some (কেহ, কিছু)'',''Better (উত্তম, শ্রেষ্ঠ)'',''He did (করেছিলেন)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-103', 'مرحبا', 'Marhaba', 'Hello', 'হ্যালো', '{''Which (যেটি, যেগুলো)'',''I (আমি)'',''Near (নিকটবর্তী, প্রায়)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-104', 'أهلا وسهلا', 'Ahlan wa sahlan', 'Welcome', 'স্বাগতম', '{''Believer (বিশ্বাসী)'',''How much (কতোটুকু)'',''Allah (আল্লাহ)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-105', 'صباح الخير', 'Sabah al-khair', 'Good morning', 'সুপ্রভাত', '{''Those who (তোমরা যারা)'',''And peace be upon you (এবং আপনার উপরও শান্তি বর্ষিত হোক)'',''Some (কেহ, কিছু)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-106', 'مساء الخير', 'Masa al-khair', 'Good evening', 'সুন্দর সন্ধ্যা', '{''Above (উপর)'',''Praise be to Allah (আল্লাহর প্রশংসা)'',''With (সাথে)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-107', 'ليلة سعيدة', 'Layla saeeda', 'Good night', 'শুভ রাত্রি', '{''He (তিনি, সে)'',''Some (কেহ, কিছু)'',''Family (দল, পরিবার)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-108', 'مع السلامة', 'Ma as-salamah', 'Goodbye', 'বিদায়', '{''Heart (অন্তর)'',''He knew (তিনি জানতেন)'',''Slave (গোলাম)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-109', 'إلى اللقاء', 'Ila al-liqaa', 'See you later', 'পরে দেখা হবে', '{''Some (কেহ, কিছু)'',''He sent down (তিনি প্রেরণ করলেন)'',''He disbelieved (অবিশ্বাস করেছিলো)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-110', 'كيف حالك', 'Kaifa haluk', 'How are you', 'আপনার কেমন আছেন', '{''Good evening (সুন্দর সন্ধ্যা)'',''He wished (ইচ্ছে পোষণ করেছিলেন)'',''Between (মধ্যবর্তী স্থানে)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-111', 'الحمد لله', 'Alhamdulillah', 'Praise be to Allah', 'আল্লাহর প্রশংসা', '{''She (সে)'',''Thank you (ধন্যবাদ)'',''Nay (বস্তুত)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-112', 'إن شاء الله', 'Insha Allah', 'If Allah wills', 'যদি আল্লাহ চান', '{''Please (অনুগ্রহ করে)'',''Messenger (দূত)'',''Way (পথ, উপায়)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-113', 'ماشاء الله', 'Masha Allah', 'What Allah has willed', 'আল্লাহ যা চেয়েছেন', '{''Thing (জিনিস, ঘটনা)'',''Right (ন্যায়, ঠিক, সত্য)'',''He was (He was)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-114', 'بارك الله فيك', 'Barak Allahu fik', 'May Allah bless you', 'আল্লাহ আপনাকে বরকত দিন', '{''No (না)'',''Fire (আগুন)'',''With (সাথে)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-115', 'جزاك الله خيرا', 'Jazak Allahu khairan', 'May Allah reward you with good', 'আল্লাহ আপনাকে উত্তম পুরস্কার দিন', '{''Right (ন্যায়, ঠিক, সত্য)'',''Messenger (দূত)'',''Way (পথ, উপায়)''}'::text[], 'greetings', 'extended-quran-words'),
  ('word-116', 'شكرا', 'Shukran', 'Thank you', 'ধন্যবাদ', '{''He knew (তিনি জানতেন)'',''Who/That (যে)'',''From (হতে, থেকে)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-117', 'عفوا', 'Afwan', 'You''re welcome', 'স্বাগতম', '{''This (এটা)'',''Excuse me (মাফ করবেন)'',''He came (তিনি এসেছিলেন)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-118', 'ربما', 'Rubama', 'Maybe', 'হয়তো', '{''May Allah reward you with good (আল্লাহ আপনাকে উত্তম পুরস্কার দিন)'',''Not (মোটেই নয়)'',''Please (অনুগ্রহ করে)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-119', 'أعتذر', 'A''tadhir', 'I apologize', 'আমি ক্ষমা চাইছি', '{''What Allah has willed (আল্লাহ যা চেয়েছেন)'',''After (পরে, পরবর্তী কালে)'',''You''''re welcome (স্বাগতম)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-120', 'عذراً', 'Udhrun', 'Excuse me', 'মাফ করবেন', '{''Truth (সত্য)'',''No (না)'',''How (কেমন, কিভাবে)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-121', 'من فضلك', 'Min fadlik', 'Please', 'অনুগ্রহ করে', '{''No (না)'',''These (এইসকল)'',''Sign/Verse (চিহ্ন/আয়াত)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-122', 'أهلا', 'Ahlan', 'Welcome', 'স্বাগতম', '{''Hello (হ্যালো)'',''You''''re welcome (স্বাগতম)'',''You both (তোমরা উভয়েই)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-123', 'أهلا بك', 'Ahlan bika', 'Welcome to you', 'আপনাকে স্বাগতম', '{''He came (He came)'',''He feared (ভয়)'',''Good night (শুভ রাত্রি)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-124', 'أهلا وسهلا بك', 'Ahlan wa sahlan bika', 'Welcome to you', 'আপনাকে স্বাগতম', '{''Allah (আল্লাহ)'',''For (জন্য)'',''Not (মোটেই নয়)''}'::text[], 'common_phrases', 'extended-quran-words'),
  ('word-125', 'أهلا وسهلا بكم', 'Ahlan wa sahlan bikum', 'Welcome to you all', 'আপনাদের সবাইকে স্বাগতম', '{''Lord (রব)'',''Excuse me (মাফ করবেন)'',''Not (মোটেই নয়)''}'::text[], 'common_phrases', 'extended-quran-words')
on conflict (id) do update set arabic = excluded.arabic, transliteration = excluded.transliteration, meaning = excluded.meaning, bengali_meaning = excluded.bengali_meaning, options = excluded.options, gender = excluded.gender, source = excluded.source;

insert into public.lesson_words (lesson_id, word_id, position) values
  ('foundations-01', 'word-1', 1),
  ('foundations-01', 'word-2', 2),
  ('foundations-01', 'word-3', 3),
  ('foundations-01', 'word-4', 4),
  ('foundations-01', 'word-5', 5),
  ('foundations-02', 'word-6', 1),
  ('foundations-02', 'word-7', 2),
  ('foundations-02', 'word-8', 3),
  ('foundations-02', 'word-9', 4),
  ('foundations-02', 'word-10', 5),
  ('foundations-03', 'word-11', 1),
  ('foundations-03', 'word-12', 2),
  ('foundations-03', 'word-13', 3),
  ('foundations-03', 'word-14', 4),
  ('foundations-03', 'word-15', 5),
  ('foundations-04', 'word-16', 1),
  ('foundations-04', 'word-17', 2),
  ('foundations-04', 'word-18', 3),
  ('foundations-04', 'word-19', 4),
  ('foundations-04', 'word-20', 5),
  ('foundations-05', 'word-21', 1),
  ('foundations-05', 'word-22', 2),
  ('foundations-05', 'word-23', 3),
  ('foundations-05', 'word-24', 4),
  ('foundations-05', 'word-25', 5),
  ('foundations-06', 'word-26', 1),
  ('foundations-06', 'word-27', 2),
  ('foundations-06', 'word-28', 3),
  ('foundations-06', 'word-29', 4),
  ('foundations-06', 'word-30', 5),
  ('foundations-07', 'word-31', 1),
  ('foundations-07', 'word-32', 2),
  ('foundations-07', 'word-33', 3),
  ('foundations-07', 'word-34', 4),
  ('foundations-07', 'word-35', 5),
  ('foundations-08', 'word-36', 1),
  ('foundations-08', 'word-37', 2),
  ('foundations-08', 'word-38', 3),
  ('foundations-08', 'word-39', 4),
  ('foundations-08', 'word-40', 5),
  ('foundations-09', 'word-41', 1),
  ('foundations-09', 'word-42', 2),
  ('foundations-09', 'word-43', 3),
  ('foundations-09', 'word-44', 4),
  ('foundations-09', 'word-45', 5),
  ('foundations-10', 'word-46', 1),
  ('foundations-10', 'word-47', 2),
  ('foundations-10', 'word-48', 3),
  ('foundations-10', 'word-49', 4),
  ('foundations-10', 'word-50', 5),
  ('foundations-11', 'word-51', 1),
  ('foundations-11', 'word-52', 2),
  ('foundations-11', 'word-53', 3),
  ('foundations-11', 'word-54', 4),
  ('foundations-11', 'word-55', 5),
  ('foundations-12', 'word-56', 1),
  ('foundations-12', 'word-57', 2),
  ('foundations-12', 'word-58', 3),
  ('foundations-12', 'word-59', 4),
  ('foundations-12', 'word-60', 5),
  ('foundations-13', 'word-61', 1),
  ('foundations-13', 'word-62', 2),
  ('foundations-13', 'word-63', 3),
  ('foundations-13', 'word-64', 4),
  ('foundations-13', 'word-65', 5),
  ('foundations-14', 'word-66', 1),
  ('foundations-14', 'word-67', 2),
  ('foundations-14', 'word-68', 3),
  ('foundations-14', 'word-69', 4),
  ('foundations-14', 'word-70', 5),
  ('foundations-15', 'word-71', 1),
  ('foundations-15', 'word-72', 2),
  ('foundations-15', 'word-73', 3),
  ('foundations-15', 'word-74', 4),
  ('foundations-15', 'word-75', 5),
  ('foundations-16', 'word-76', 1),
  ('foundations-16', 'word-77', 2),
  ('foundations-16', 'word-78', 3),
  ('foundations-16', 'word-79', 4),
  ('foundations-16', 'word-80', 5),
  ('foundations-17', 'word-81', 1),
  ('foundations-17', 'word-82', 2),
  ('foundations-17', 'word-83', 3),
  ('foundations-17', 'word-84', 4),
  ('foundations-17', 'word-85', 5),
  ('foundations-18', 'word-86', 1),
  ('foundations-18', 'word-87', 2),
  ('foundations-18', 'word-88', 3),
  ('foundations-18', 'word-89', 4),
  ('foundations-18', 'word-90', 5),
  ('foundations-19', 'word-91', 1),
  ('foundations-19', 'word-92', 2),
  ('foundations-19', 'word-93', 3),
  ('foundations-19', 'word-94', 4),
  ('foundations-19', 'word-95', 5),
  ('foundations-20', 'word-96', 1),
  ('foundations-20', 'word-97', 2),
  ('foundations-20', 'word-98', 3),
  ('foundations-20', 'word-99', 4),
  ('foundations-20', 'word-100', 5),
  ('foundations-21', 'word-101', 1),
  ('foundations-21', 'word-102', 2),
  ('foundations-21', 'word-103', 3),
  ('foundations-21', 'word-104', 4),
  ('foundations-21', 'word-105', 5),
  ('foundations-22', 'word-106', 1),
  ('foundations-22', 'word-107', 2),
  ('foundations-22', 'word-108', 3),
  ('foundations-22', 'word-109', 4),
  ('foundations-22', 'word-110', 5),
  ('foundations-23', 'word-111', 1),
  ('foundations-23', 'word-112', 2),
  ('foundations-23', 'word-113', 3),
  ('foundations-23', 'word-114', 4),
  ('foundations-23', 'word-115', 5),
  ('foundations-24', 'word-116', 1),
  ('foundations-24', 'word-117', 2),
  ('foundations-24', 'word-118', 3),
  ('foundations-24', 'word-119', 4),
  ('foundations-24', 'word-120', 5),
  ('foundations-25', 'word-121', 1),
  ('foundations-25', 'word-122', 2),
  ('foundations-25', 'word-123', 3),
  ('foundations-25', 'word-124', 4),
  ('foundations-25', 'word-125', 5)
on conflict (lesson_id, word_id) do update set position = excluded.position;

